In [1]:
from snpc import SNPC
import pandas as pd
import numpy as np

In [2]:
a_d = pd.read_csv('new_adult.csv', index_col = [0])
income = a_d['income']
inc = pd.DataFrame(np.array(income), columns= ['labels'])
a_d.drop('income', axis= 1, inplace = True)

In [3]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
x_train, x_val, y_train, y_val = train_test_split(np.array(a_d)[:6000], np.array(inc)[:6000], test_size=0.3, random_state=42)

In [9]:
model = SNPC(2)
model.fit(x_train, y_train)

Acc.......78.02380952380953, loss......0.22658467134112062
Acc.......78.71428571428571, loss......0.2185320470293008
Acc.......79.23809523809524, loss......0.21392738209711937
Acc.......79.5952380952381, loss......0.21097788320825858
Acc.......79.76190476190477, loss......0.20890632558448818
Acc.......79.85714285714286, loss......0.20701017872621186
Acc.......80.21428571428572, loss......0.2050604720623013
Acc.......80.71428571428572, loss......0.20331813394599435
Acc.......80.57142857142857, loss......0.2018611634636661
Acc.......80.71428571428572, loss......0.2006569345897449
Acc.......80.88095238095238, loss......0.19966581842450615
Acc.......80.80952380952381, loss......0.1988178877004871
Acc.......81.04761904761905, loss......0.19811063740834567
Acc.......81.04761904761905, loss......0.19754220335338277
Acc.......81.0, loss......0.19708310170884039
Acc.......81.02380952380952, loss......0.19670652404394207
Acc.......81.04761904761905, loss......0.19639344320061514
Acc.......81.023

(array([[ 2.89533137e+00,  1.13155454e-01,  3.65441689e-01,
          1.07120960e+01,  6.07227029e+00,  2.36976295e+00,
         -6.32357322e-01, -5.08239029e+00,  5.62353900e-01,
          5.46788291e-01,  1.17491576e-01, -2.42287339e-01,
          5.45497814e-01,  8.13245059e-01,  5.29232195e-01,
          4.28339454e-03, -9.11825429e-01],
        [ 1.26630059e+00, -1.09695626e+00,  1.05892804e+00,
          1.30772136e+00,  3.61438616e+00,  4.61875496e-01,
         -1.99194682e-01, -1.82550100e+00,  8.72979035e-01,
         -6.54399132e-05, -1.35074123e-01,  2.61885499e-01,
          5.58469595e-01, -4.44744954e-01,  4.98757479e-01,
          1.41836771e-02,  3.72990418e-01],
        [ 3.91003344e+00,  2.68033507e+00,  1.55762923e+00,
          7.01805623e+00, -6.06793486e+00, -8.34112914e-01,
          3.03967428e+00,  4.26355307e+00,  1.61846735e-01,
         -4.93595360e-01,  7.11084888e-01,  5.65504689e-01,
         -1.03581440e+00, -8.74437562e-01, -4.40681274e-01,
         -1.

In [10]:
model.evaluate(x_val, y_val)

80.27777777777779

In [11]:
model.predict_all(x_val)

array([0, 0, 0, ..., 0, 0, 0])

In [7]:
model.predict_all(x_val, return_scores=True)

[array([0.3930976, 0.6069024]),
 array([0.47941444, 0.52058556]),
 array([0.34123882, 0.65876118]),
 array([0.5021063, 0.4978937]),
 array([0.36272843, 0.63727157]),
 array([0.48434007, 0.51565993]),
 array([0.46775967, 0.53224033]),
 array([0.41487544, 0.58512456]),
 array([0.34276329, 0.65723671]),
 array([0.43112644, 0.56887356]),
 array([0.45642535, 0.54357465]),
 array([0.44638841, 0.55361159]),
 array([0.36514527, 0.63485473]),
 array([0.43228584, 0.56771416]),
 array([0.48623918, 0.51376082]),
 array([0.417512, 0.582488]),
 array([0.53428701, 0.46571299]),
 array([0.51939452, 0.48060548]),
 array([0.49865419, 0.50134581]),
 array([0.43520082, 0.56479918]),
 array([0.49244214, 0.50755786]),
 array([0.44638841, 0.55361159]),
 array([0.44367415, 0.55632585]),
 array([0.5021063, 0.4978937]),
 array([0.4418868, 0.5581132]),
 array([0.48382127, 0.51617873]),
 array([0.41964404, 0.58035596]),
 array([0.37391738, 0.62608262]),
 array([0.46058175, 0.53941825]),
 array([0.47060245, 0.5293

In [8]:
#try for mean initialization
trained_model = SNPC(num_prototypes_per_class=1, initialization_type='random')
prototypes,proto_labels = trained_model.fit(x_train, y_train)
trained_model.evaluate(x_val, y_val)

Acc.......61.595238095238095, loss......0.3840844098851329
Acc.......64.83333333333333, loss......0.35294212318010376
Acc.......74.73809523809524, loss......0.25290148096857873
Acc.......74.83333333333333, loss......0.2518150863790586
Acc.......74.83333333333333, loss......0.251712790967368
Acc.......74.83333333333333, loss......0.25169276723775846
Acc.......74.83333333333333, loss......0.25168472963025196
Acc.......74.83333333333333, loss......0.2516804411946925
Acc.......74.83333333333333, loss......0.2516777848147512
Acc.......74.83333333333333, loss......0.2516759809729955
Acc.......74.83333333333333, loss......0.25167467729792253
Acc.......74.83333333333333, loss......0.2516736916991439
Acc.......74.83333333333333, loss......0.2516729207437468
Acc.......74.83333333333333, loss......0.25167230138067087
Acc.......74.83333333333333, loss......0.25167179301063836
Acc.......74.83333333333333, loss......0.25167136832128223
Acc.......74.83333333333333, loss......0.2516710082687666
Acc...

75.1111111111111