In [1]:
import numpy as np

In [2]:
from sklearn import datasets
E, F = datasets.load_iris(return_X_y= True)

In [3]:
from sklearn.preprocessing import MinMaxScaler
Scale = MinMaxScaler()
Scaled = Scale.fit_transform(E)


In [4]:
split = (0.8,0.2)
seed = 45


rng = np.random.default_rng(seed)

cuts = (np.array(split) * len(E)).astype(int)
i_train, i_val = np.split(rng.permutation(len(E)), cuts[:-1])

x_train, y_train = Scaled[i_train], F[i_train]
x_val, y_val = Scaled[i_val], F[i_val]

In [5]:
from rlvq import RLVQ

In [6]:
trained_model = RLVQ(num_prototypes_per_class=1, initialization_type='random')

In [7]:
trained_model.fit(x_train, y_train)

(array([[0.20508397, 0.61558256, 0.07659336, 0.05774307],
        [0.47086238, 0.33575743, 0.53882247, 0.48809098],
        [0.66546834, 0.43593781, 0.79237642, 0.82147855]]),
 array([0, 1, 2]),
 array([1.59125697e-05, 7.40925441e-05, 5.91282204e-01, 4.08627791e-01]))

In [8]:
#evaluatte on test set
trained_model.evaluate(x_val, y_val)

96.66666666666667