In [1]:
from rslvq import RSLVQ
import pandas as pd
import numpy as np

In [2]:
b_c_data = pd.read_csv('data.csv')
b_c_data.columns
b_c_data.drop(['id', 'Unnamed: 32'], axis = 1, inplace= True)
label = b_c_data['diagnosis'].replace({'M': 0, 'B': 1})
train_data = b_c_data.drop(['diagnosis'], axis = 1)

In [3]:
#scale data between 0 and 1
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
X = scale.fit_transform(train_data)
norm_t_data = pd.DataFrame(X, columns = train_data.columns, index = train_data.index)

In [4]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
x_train, x_val, y_train, y_val = train_test_split(np.array(norm_t_data), np.array(label), test_size=0.3, random_state=42)

In [5]:
trained_model = RSLVQ(num_prototypes_per_class=1, initialization_type='random')

In [6]:
from rslvq_utils_ import cross_validation

In [12]:
cross_validation(trained_model, np.array(norm_t_data),np.array(label), 5, return_best_split=True)

Acc.......92.10526315789474, loss......1613.9839824380053
Acc.......92.54385964912281, loss......2441.0936112401146
Acc.......92.54385964912281, loss......3084.0506135373307
Acc.......92.54385964912281, loss......3622.6965015551455
Acc.......92.54385964912281, loss......4092.9858099563507
Acc.......92.54385964912281, loss......4514.726376019354
Acc.......92.54385964912281, loss......4900.26307012894
Acc.......92.54385964912281, loss......5257.932988331726
Acc.......92.54385964912281, loss......5593.687803587065
Acc.......92.54385964912281, loss......5911.954185013936
Acc.......92.54385964912281, loss......6216.133441065673
Acc.......92.54385964912281, loss......6508.911869267855
Acc.......92.54385964912281, loss......6792.463494573329
Acc.......92.54385964912281, loss......7068.587742582586
Acc.......92.54385964912281, loss......7338.805874864017
Acc.......92.54385964912281, loss......7604.430320789011
Acc.......92.54385964912281, loss......7866.6156780338715
Acc.......92.5438596491228

(array([[0.40318993, 0.38451133, 0.40847212, ..., 0.73333333, 0.28346146,
         0.32638069],
        [0.32651806, 0.21812648, 0.3080644 , ..., 0.15591065, 0.19258821,
         0.0733963 ],
        [0.09754366, 0.31078796, 0.11250086, ..., 0.39347079, 0.30948157,
         0.33097206],
        ...,
        [0.11756354, 0.38214406, 0.11277728, ..., 0.22395189, 0.25882121,
         0.24314574],
        [0.83529746, 0.40209672, 0.84106143, ..., 0.85051546, 0.31381825,
         0.27331759],
        [0.62989256, 0.15657761, 0.63098611, ..., 0.55841924, 0.15750049,
         0.14259478]]),
 array([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0

In [8]:
prototypes,proto_labels = trained_model.fit(x_train, y_train)

Acc.......94.47236180904522, loss......1224.9299558253674


Acc.......94.9748743718593, loss......1882.600192958845
Acc.......95.7286432160804, loss......2394.812963298321
Acc.......95.97989949748744, loss......2822.802170359381
Acc.......96.4824120603015, loss......3192.571392044802
Acc.......96.73366834170855, loss......3518.1964461895127
Acc.......96.73366834170855, loss......3808.632931508757
Acc.......96.73366834170855, loss......4070.1403740412984
Acc.......96.98492462311557, loss......4307.3505779462575
Acc.......96.98492462311557, loss......4523.827131966116
Acc.......96.98492462311557, loss......4722.392520876385
Acc.......96.98492462311557, loss......4905.332945731817
Acc.......96.98492462311557, loss......5074.533002455224
Acc.......96.98492462311557, loss......5231.567881132947
Acc.......97.23618090452261, loss......5377.7687748417
Acc.......97.23618090452261, loss......5514.270785012147
Acc.......97.23618090452261, loss......5642.049003572453
Acc.......97.23618090452261, loss......5761.946349771049
Acc.......97.23618090452261, loss

In [9]:
#evaluatte on test set
trained_model.evaluate(x_val, y_val)

98.24561403508771

In [10]:
#use command predict_all for arrays of points
trained_model.predict_all(x_val)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [11]:
#try for mean initialization
trained_model = RSLVQ(num_prototypes_per_class=1, initialization_type='mean')
prototypes,proto_labels = trained_model.fit(x_train, y_train)
trained_model.evaluate(x_val, y_val)

Acc.......94.72361809045226, loss......1252.8202439524991


Acc.......95.22613065326632, loss......1902.2794470070205
Acc.......95.7286432160804, loss......2413.8799064375626
Acc.......95.97989949748744, loss......2842.0623507775654
Acc.......96.23115577889448, loss......3211.7113971584185
Acc.......96.4824120603015, loss......3536.885883306425
Acc.......96.73366834170855, loss......3826.661615345486
Acc.......96.73366834170855, loss......4087.3922287903133
Acc.......96.98492462311557, loss......4323.77005587557
Acc.......96.98492462311557, loss......4539.396361929629
Acc.......96.98492462311557, loss......4737.116576549051
Acc.......96.98492462311557, loss......4919.230142596437
Acc.......96.98492462311557, loss......5087.628445657924
Acc.......97.23618090452261, loss......5243.8892554598715
Acc.......97.23618090452261, loss......5389.3437256661
Acc.......97.23618090452261, loss......5525.125420769733
Acc.......97.23618090452261, loss......5652.207166540438
Acc.......97.23618090452261, loss......5771.429390529116
Acc.......97.23618090452261, l

98.24561403508771